profiles:
  k8s-apparmor-example-deny-write: |-
    #include <tunables/global>
    profile k8s-apparmor-example-deny-write flags=(attach_disconnected) {
      #include <abstractions/base>

      file,
      
      deny /** w,
    }

# securityPolicies:
#   psp-example:
#     defaultProfile: localhost/k8s-apparmor-example-deny-write
#     allowedProfiles:
#     - localhost/k8s-apparmor-example-deny-write
#     spec:
#       privileged: false
#       seLinux:
#         rule: RunAsAny
#       supplementalGroups:
#         rule: RunAsAny
#       runAsUser:
#         rule: RunAsAny
#       fsGroup:
#         rule: RunAsAny
#       volumes:
#         - '*'
