profiles:
  k8s-apparmor-example-deny-write: |-
    #include <tunables/global>
    profile k8s-apparmor-example-deny-write flags=(attach_disconnected) {
      #include <abstractions/base>

      file,
      
      deny /** w,
    }